// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtjWRiUs3tVGMF7miqrzphCii878kuxCM',
    appId: '1:737322050994:web:f92fd5cf3f10190e4ef0ab',
    messagingSenderId: '737322050994',
    projectId: 'confapp-8f29e',
    authDomain: 'confapp-8f29e.firebaseapp.com',
    storageBucket: 'confapp-8f29e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU_WbROUHAv_nEHGMkqmZ845LrotRrsmA',
    appId: '1:737322050994:android:af4ad36d1272856b4ef0ab',
    messagingSenderId: '737322050994',
    projectId: 'confapp-8f29e',
    storageBucket: 'confapp-8f29e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANMVQGwyz2GF1acdwow7pr1zJtciyO5NM',
    appId: '1:737322050994:ios:c1df2c11638f4ba64ef0ab',
    messagingSenderId: '737322050994',
    projectId: 'confapp-8f29e',
    storageBucket: 'confapp-8f29e.firebasestorage.app',
    iosBundleId: 'com.example.confApp',
  );

}